

eureka:
  client:
    service-url:
      defaultZone: http://admin:123@localhost:9000/eureka
spring:
  application:
    name: 04provider-eureka  #名字和01的提供者一样，默认是一个集群，服务中心就会自动启动负载均衡机制

server:
  port: 8070